# Generated by Django 4.1.1 on 2022-10-05 20:06

from django.db import migrations, models
import email.utils


class Migration(migrations.Migration):

    dependencies = [
        ('myFavBooks', '0002_alter_book_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(default=email.utils.localtime),
        ),
    ]
