# Generated by Django 4.1.1 on 2022-09-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuthorsApp', '0003_author_delete_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
