# Generated by Django 4.1.1 on 2022-10-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginApp', '0002_message_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
