# Generated by Django 4.1.1 on 2022-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTvShowsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
